package philosophyjava.examples.example10;

public enum Watercolors {
    ZINC,
    LEM0N_YELL0W,
    MEDIUM_YELLOW,
    DEEP_YELLOW,
    ORANGE,
    BRILLIANT_RED,
    CRIMSON,
    MAGENTA,
    ROSE_MADDER,
    VI0LET,
    CERULEAN_BLUE_HUE,
    PHTHALO_BLUE,
    ULTRAMARINE,
    COBALT_BLUE_HUE,
    PERMANENT_GREEN,
    VIRIDIAN_HUE,
    SAP_GREEN,
    YELLOW_OCHRE,
    BURNT_SIENNA,
    RAW_UMBER,
    BURNT_UMBER,
    PAYNES_GRAY,
    IVORY_BLACK
}
